// Ilustrações próprias (desenhos SVG em public/img/ilustracoes/), usadas quando
// o produto ainda não tem foto. Sempre exibidas com o selo "Imagem ilustrativa".
export const ILLUSTRATIONS = {
  hamburguer: 'Hambúrguer clássico',
  'hamburguer-bacon': 'Hambúrguer com bacon',
  'hamburguer-salada': 'Hambúrguer com salada',
  'hamburguer-ovo': 'Hambúrguer com ovo',
  'hamburguer-tudo': 'Hambúrguer completo',
  'smash-duplo': 'Smash duplo',
  frango: 'Sanduíche de frango',
  veggie: 'Hambúrguer vegetariano',
  combo: 'Combo (lanche, batata e bebida)',
  'combo-familia': 'Combo família',
  batata: 'Batata frita',
  'batata-cheddar': 'Batata com cheddar',
  'onion-rings': 'Anéis de cebola',
  nuggets: 'Nuggets',
  'refrigerante-lata': 'Refrigerante lata',
  'refrigerante-2l': 'Refrigerante garrafa',
  suco: 'Suco',
  agua: 'Água',
  milkshake: 'Milk-shake',
  brownie: 'Brownie',
  'petit-gateau': 'Petit gâteau',
  pudim: 'Pudim',
  // ampliação 06/10/2026
  'x-calabresa': 'Hambúrguer com calabresa',
  'x-frango': 'Sanduíche de frango com catupiry',
  'x-cheddar': 'Hambúrguer com cheddar cremoso',
  smash: 'Smash simples',
  'smash-bacon': 'Smash com bacon',
  'smash-triplo': 'Smash triplo',
  'smash-picante': 'Smash picante',
  'premium-costela': 'Premium: costela',
  'premium-picanha': 'Premium: picanha',
  'premium-gorgonzola': 'Premium: gorgonzola e mel',
  'premium-onion': 'Premium: cebola crispy',
  'premium-bbq': 'Premium: barbecue',
  hotdog: 'Cachorro-quente',
  'hotdog-especial': 'Cachorro-quente especial',
  'hotdog-bacon': 'Cachorro-quente com bacon',
  'misto-quente': 'Misto quente',
  'sanduiche-natural': 'Sanduíche natural',
  beirute: 'Beirute',
  mandioca: 'Mandioca frita',
  'isca-frango': 'Iscas de frango',
  'porcao-mista': 'Porção mista',
  'batata-rustica': 'Batata rústica',
  kids: 'Lanche kids',
  'kids-nuggets': 'Nuggets kids',
  'molho-maionese': 'Molho: maionese',
  'molho-barbecue': 'Molho: barbecue',
  'molho-cheddar': 'Molho: cheddar',
  'molho-verde': 'Molho: maionese verde',
  'refrigerante-600': 'Refrigerante 600 ml',
  limonada: 'Limonada',
  'cha-gelado': 'Chá gelado',
  acai: 'Açaí (copo)',
  'acai-grande': 'Açaí (copo grande)',
  'acai-tigela': 'Açaí na tigela',
  churros: 'Churros',
  sorvete: 'Sorvete',
  mousse: 'Mousse',
};

export const illustrationList = () => Object.entries(ILLUSTRATIONS).map(([key, label]) => ({ key, label }));
